import "~/styles/globals.css";

import { Montserrat } from 'next/font/google';

import { type Metadata } from "next";

import { Toaster } from "~/components/ui/sonner";

import { TRPCReactProvider } from "~/trpc/react";
import { getServerAuthSession } from "~/server/auth";
import { ReduxProvider } from "./_lib/context/redux";

import { api } from "~/trpc/server";
// import { Provider } from "react-redux";
// import store from "~/client-store";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const montserrat = Montserrat({ subsets: ['latin'] });

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  // await api.schedule.generate({groupId: 'is-313'})
  
  return (
    <html lang="ru" className={`${montserrat.className}`}>
      <body>
        <TRPCReactProvider>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </TRPCReactProvider>
        <Toaster />
      </body>
    </html>
  );
}
